In [302]:
from sklearn import datasets

In [303]:
data = datasets.load_iris()

In [304]:
X = data.data
y = data.target
len(y)

150

In [305]:
from sklearn.model_selection import train_test_split

In [306]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [307]:
def get_score(model,X_train,X_test,y_train,y_test):
    
    model.fit(X_train,y_train)
    
    return model.score(X_test,y_test)

In [308]:
from sklearn import linear_model
l_model = linear_model.LogisticRegression()

In [309]:
from sklearn import svm
svc = svm.SVC()

In [310]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [311]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 40)

In [312]:
print(get_score(l_model,X_train,X_test,y_train,y_test))

1.0


In [313]:
from sklearn.model_selection import KFold,StratifiedKFold

In [314]:
sfold = StratifiedKFold(n_splits = 3)

In [315]:
lscore = []
svc_score = []
rfc_score = []
dtc_score = []

In [316]:
for train_index,test_index in sfold.split(data.data,data.target):
    X_train,X_test,y_train,y_test = data.data[train_index],data.data[test_index],data.target[train_index],data.target[test_index]
    lscore.append(get_score(l_model,X_train,X_test,y_train,y_test))
    svc_score.append(get_score(svc,X_train,X_test,y_train,y_test))
    rfc_score.append(get_score(rfc,X_train,X_test,y_train,y_test))
    dtc_score.append(get_score(dtc,X_train,X_test,y_train,y_test))
    


C:\Users\Abhi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [317]:
svc_score

[0.96, 0.98, 0.94]

In [318]:
rfc_score  

[0.98, 0.94, 0.94]

In [319]:
lscore

[0.98, 0.96, 0.98]

In [320]:
dtc_score

[0.98, 0.92, 1.0]

(Or)  We Can Use cross_val_score of Sklearn

In [321]:
from sklearn.model_selection import cross_val_score

In [322]:
l_scores = cross_val_score(l_model,data.data,data.target,cv=3)
l_scores

C:\Users\Abhi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [323]:
svc_scores = cross_val_score(svc,data.data,data.target,cv=3)
svc_scores

array([0.96, 0.98, 0.94])

In [324]:
rfc_scores = cross_val_score(rfc,data.data,data.target,cv=3)
rfc_scores

array([0.98, 0.94, 0.96])

In [325]:
dtc_scores = cross_val_score(dtc,data.data,data.target,cv=3)
dtc_scores

array([0.98, 0.92, 1.  ])

In [326]:
import numpy as np

In [327]:
l_mean = np.mean(l_scores)
l_mean

0.9733333333333333

In [328]:
svc_mean = np.mean(svc_scores)
svc_mean

0.96

In [329]:
rfc_mean = np.mean(rfc_scores)
rfc_mean

0.96

In [330]:
dtc_mean = np.mean(dtc_scores)
dtc_mean

0.9666666666666667

Best Classifier So Far Is....LogisticRegression model